In [4]:
# Dependencies
import pandas as pd
import netCDF4

In [6]:
dt = 202305
nc = netCDF4.Dataset(f'../resources/GPM_3IMERGM_MO/3B-MO.MS.MRG.3IMERG.{dt}01-S000000-E235959.05.V07B.HDF5.nc4')
nc.variables.keys()

dict_keys(['precipitation', 'lat', 'lon', 'time'])

In [7]:
prcp = nc.variables['precipitation']
lat = nc.variables['lat']
lon = nc.variables['lon']
prcp

<class 'netCDF4._netCDF4.Variable'>
float32 precipitation(time, lon, lat)
    DimensionNames: time,lon,lat
    Units: mm/hr
    units: mm/hr
    _FillValue: -9999.9
    CodeMissingValue: -9999.9
    LongName: Merged microwave-infrared-gauge precipitation estimate
    origname: precipitation
    fullnamepath: /Grid/precipitation
    coordinates: Grid_time Grid_lon Grid_lat
unlimited dimensions:
current shape = (1, 111, 111)
filling on

In [8]:
prcp.dimensions

('time', 'lon', 'lat')

In [9]:
# extract lat/lon values (in degrees)
lons = nc.variables['lon'][:]
lats = nc.variables['lat'][:]
lons.data[0],lons.data[-1],lats.data[0],lats.data[-1]

(-124.95, -113.95, 31.949999, 42.95)

In [11]:
print(lats)

[31.949999 32.05     32.149998 32.25     32.35     32.45     32.55
 32.649998 32.75     32.85     32.95     33.05     33.149998 33.25
 33.35     33.45     33.55     33.649998 33.75     33.85     33.95
 34.05     34.149998 34.25     34.35     34.45     34.55     34.649998
 34.75     34.85     34.95     35.05     35.149998 35.25     35.35
 35.45     35.55     35.649998 35.75     35.85     35.95     36.05
 36.149998 36.25     36.35     36.45     36.55     36.649998 36.75
 36.85     36.95     37.05     37.149998 37.25     37.35     37.45
 37.55     37.649998 37.75     37.85     37.95     38.05     38.149998
 38.25     38.35     38.45     38.55     38.649998 38.75     38.85
 38.95     39.05     39.149998 39.25     39.35     39.45     39.55
 39.649998 39.75     39.85     39.95     40.05     40.149998 40.25
 40.35     40.45     40.55     40.649998 40.75     40.85     40.95
 41.05     41.149998 41.25     41.35     41.45     41.55     41.649998
 41.75     41.85     41.95     42.05     42.149998 42.25     42.35
 42.45     42.55     42.649998 42.75     42.85     42.95    ]

In [12]:
df = pd.DataFrame(
    prcp[0,:,:].data,
    index = [x/100 for x in range( round(100*lons[0]), round(100*lons[-1]+10), 10)],
    columns = [x/100 for x in range( round(100*lats[0]), round(100*lats[-1]+10), 10)], 
)
df.index.names = ['lon']
df

,31.95,32.05,32.15,32.25,32.35,32.45,32.55,32.65,32.75,32.85,...,42.05,42.15,42.25,42.35,42.45,42.55,42.65,42.75,42.85,42.95
lon,,,,,,,,,,,,,,,,,,,,,
-124.95,0.009,0.009,0.007,0.007,0.007,0.007,0.009,0.012,0.016,0.014,...,0.078,0.076,0.084,0.087,0.078,0.065,0.047,0.036,0.040,0.045
-124.85,0.009,0.007,0.006,0.006,0.005,0.004,0.005,0.006,0.015,0.014,...,0.078,0.063,0.074,0.087,0.088,0.073,0.057,0.038,0.040,0.045
-124.75,0.010,0.008,0.009,0.006,0.005,0.005,0.006,0.007,0.011,0.012,...,0.077,0.068,0.079,0.078,0.078,0.065,0.068,0.055,0.043,0.052
-124.65,0.009,0.009,0.009,0.007,0.006,0.005,0.005,0.006,0.009,0.013,...,0.066,0.069,0.071,0.070,0.072,0.062,0.059,0.063,0.050,0.053
-124.55,0.011,0.010,0.009,0.007,0.005,0.003,0.004,0.006,0.008,0.010,...,0.064,0.062,0.069,0.067,0.062,0.055,0.057,0.058,0.054,0.054
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
-114.35,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.001,0.002,...,0.096,0.089,0.107,0.113,0.128,0.103,0.080,0.067,0.058,0.050
-114.25,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.001,0.001,0.001,...,0.093,0.091,0.100,0.096,0.105,0.102,0.092,0.056,0.053,0.056
-114.15,0.000,0.000,0.000,0.002,0.000,0.001,0.000,0.001,0.001,0.001,...,0.090,0.074,0.081,0.075,0.085,0.086,0.075,0.051,0.042,0.038
-114.05,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.001,0.001,0.003,...,0.082,0.072,0.068,0.074,0.071,0.079,0.074,0.068,0.057,0.037
-113.95,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.001,0.002,0.004,...,0.063,0.058,0.061,0.066,0.064,0.063,0.074,0.060,0.055,0.048

In [64]:
df[31.95][-124.95]

0.009000001

In [78]:
31*24*prcp[0,0,0].data[()]

6.696000404655933