In [1]:
# Dependencies
import pandas as pd

In [9]:
# Steup data frame and dates for daily precipitation data by year
year = 2012
df = pd.DataFrame(columns=['station'])
dts = pd.date_range(str(year) + "-01-01", str(year) + "-12-31", freq="D")

In [10]:
# Retrieve daily precipitation data for year and merge into dataframe
for dt in dts:
    d = str(dt.date())
    dt_df = pd.read_csv(f'../outputs/prcp/{year}/csv/{d}.csv')
    df = df.merge(dt_df, on='station', how='outer')

In [5]:
# Output csv for stations with data
df['station'].to_csv(f'../outputs/prcp/{year}/CA_{year}_stns.csv',index=False)

In [6]:
# Compare stations from precipiation data to ghcnd-station.csv and check to make sure there isn't missing data
ghcnd_df = pd.read_csv('../outputs/prcp/ghcnd-stations.csv')
r = [x for x in df['station'].to_list() if not x in ghcnd_df['station'].to_list()]
len(r)

0

In [7]:
# Get station info from ghcnd-station.csv for station in precipitation data
stn_df = ghcnd_df[ghcnd_df['station'].isin(df['station'].to_list())].reset_index(drop=True)
stn_df

,station,lat,lon,elev,name
0,US1CAAL0001,37.8123,-122.2160,113.4,CA PIEDMONT 1.0 SE
1,US1CAAL0002,37.7075,-122.0687,87.5,CA CASTRO VALLEY 0.5 WSW
2,US1CAAL0003,37.7169,-122.0585,163.4,CA CASTRO VALLEY 0.4 NNE
3,US1CAAL0004,37.6483,-121.8745,107.0,CA PLEASANTON 1.8 SSE
4,US1CAAL0006,37.8319,-122.2503,58.2,CA OAKLAND 4.4 NNW
...,...,...,...,...,...
1007,USW00093241,38.3775,-121.9586,31.7,CA VACAVILLE/NUT TREE AP ASOS
1008,USW00093242,36.9850,-120.1106,76.5,CA MADERA MUNI AP
1009,USW00093243,37.2381,-120.8825,23.8,CA MERCED 23 WSW CRN
1010,USW00093245,38.3208,-123.0747,19.2,CA BODEGA 6 WSW CRN
1011,USW00094299,41.4836,-120.5614,1335.9,CA ALTURAS MUNI AP

In [95]:
# Output csv for relevant station info
stn_df.to_csv(f'../outputs/prcp/{year}/CA_{year}_coords.csv',index=False)

In [8]:
# Add Station Information to Dataframe
df = df.merge(stn_df, on='station')

In [9]:
# Fill na with zeros and preview
df = df.fillna(0.0)
df

,station,2012-01-01,2012-01-02,2012-01-03,2012-01-04,2012-01-05,2012-01-06,2012-01-07,2012-01-08,2012-01-09,...,2012-12-26,2012-12-27,2012-12-28,2012-12-29,2012-12-30,2012-12-31,lat,lon,elev,name
0,US1CAAL0001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,26.7,2.3,0.0,2.5,0.0,0.0,37.8123,-122.2160,113.4,CA PIEDMONT 1.0 SE
1,US1CAAL0002,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,37.7075,-122.0687,87.5,CA CASTRO VALLEY 0.5 WSW
2,US1CAAL0003,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,18.8,1.8,0.0,2.0,0.0,0.0,37.7169,-122.0585,163.4,CA CASTRO VALLEY 0.4 NNE
3,US1CAAL0004,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,15.0,1.0,0.0,3.6,0.0,0.0,37.6483,-121.8745,107.0,CA PLEASANTON 1.8 SSE
4,US1CAAL0006,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,24.1,0.0,0.0,1.8,0.0,0.0,37.8319,-122.2503,58.2,CA OAKLAND 4.4 NNW
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1007,USW00093241,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,38.3775,-121.9586,31.7,CA VACAVILLE/NUT TREE AP ASOS
1008,USW00093242,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,7.4,0.0,0.0,0.0,0.0,0.0,36.9850,-120.1106,76.5,CA MADERA MUNI AP
1009,USW00093243,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,37.2381,-120.8825,23.8,CA MERCED 23 WSW CRN
1010,USW00093245,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.1,0.3,12.3,2.8,0.0,0.5,38.3208,-123.0747,19.2,CA BODEGA 6 WSW CRN
1011,USW00094299,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.3,0.3,0.5,0.0,0.3,0.0,41.4836,-120.5614,1335.9,CA ALTURAS MUNI AP

In [98]:
# Output dataframe to csv
df.to_csv(f'../outputs/prcp/{year}/CA_{year}_prcp_data.csv',index=False)