In [2]:
# Dependencies
import pandas as pd
import requests
import time
from api_key import noaa_key

In [37]:
# Setup to retrive daily summary data from NOAA NCEI by year
year = 2012
dts = pd.date_range(str(year)+"-01-01", str(year)+"-12-31", freq="D")
dts_chk = []

In [38]:
# Setup parameters for queries
url = "https://www.ncei.noaa.gov/cdo-web/api/v2/data?"
ds_id='GHCND'
dt_id='PRCP'
loc_id='FIPS:06'
limit=1000
# loop through dates and retrieve data and write to csv by date
for dt in dts:
    d = str(dt.date())
    print(d)
    q_url = f"{url}datasetid={ds_id}&datatypeid={dt_id}&locationid={loc_id}&startdate={d}&enddate={d}&units=metric&limit={limit}"
    try: 
        response = requests.get(q_url, headers={'token': noaa_key}).json()
        df = pd.DataFrame(response['results'])
        df['station'] = df['station'].str.slice(6,17)
        df = df[['station','value']].rename(columns={'value':d})
        df.to_csv(f'outputs/prcp/{year}/csv/{d}.csv',index=False)
    except:
        dts_chk.append(d)
        print(f'{d} failed')
    time.sleep(1)

2012-01-01
2012-01-02
2012-01-03
2012-01-04
2012-01-05
2012-01-06
2012-01-07
2012-01-08
2012-01-09
2012-01-10
2012-01-11
2012-01-12
2012-01-13
2012-01-14
2012-01-15
2012-01-16
2012-01-17
2012-01-18
2012-01-19
2012-01-20
2012-01-21
2012-01-22
2012-01-23
2012-01-24
2012-01-25
2012-01-26
2012-01-26 failed
2012-01-27
2012-01-28
2012-01-29
2012-01-30
2012-01-31
2012-02-01
2012-02-02
2012-02-03
2012-02-04
2012-02-05
2012-02-06
2012-02-07
2012-02-08
2012-02-08 failed
2012-02-09
2012-02-10
2012-02-11
2012-02-12
2012-02-13
2012-02-14
2012-02-15
2012-02-16
2012-02-17
2012-02-18
2012-02-19
2012-02-20
2012-02-21
2012-02-22
2012-02-23
2012-02-24
2012-02-25
2012-02-26
2012-02-27
2012-02-28
2012-02-29
2012-03-01
2012-03-02
2012-03-03
2012-03-04
2012-03-05
2012-03-06
2012-03-07
2012-03-08
2012-03-09
2012-03-10
2012-03-11
2012-03-12
2012-03-13
2012-03-14
2012-03-15
2012-03-16
2012-03-17
2012-03-17 failed
2012-03-18
2012-03-19
2012-03-20
2012-03-21
2012-03-22
2012-03-23
2012-03-24
2012-03-25
2012-03-26
2012-03-27
2012-03-27 failed
2012-03-28
2012-03-29
2012-03-30
2012-03-31
2012-04-01
2012-04-02
2012-04-03
2012-04-03 failed
2012-04-04
2012-04-05
2012-04-06
2012-04-06 failed
2012-04-07
2012-04-08
2012-04-09
2012-04-10
2012-04-11
2012-04-12
2012-04-13
2012-04-14
2012-04-15
2012-04-16
2012-04-16 failed
2012-04-17
2012-04-17 failed
2012-04-18
2012-04-19
2012-04-20
2012-04-21
2012-04-22
2012-04-23
2012-04-24
2012-04-25
2012-04-26
2012-04-27
2012-04-28
2012-04-29
2012-04-30
2012-05-01
2012-05-02
2012-05-03
2012-05-04
2012-05-05
2012-05-06
2012-05-06 failed
2012-05-07
2012-05-08
2012-05-09
2012-05-10
2012-05-11
2012-05-12
2012-05-13
2012-05-14
2012-05-15
2012-05-16
2012-05-16 failed
2012-05-17
2012-05-17 failed
2012-05-18
2012-05-19
2012-05-20
2012-05-21
2012-05-22
2012-05-23
2012-05-24
2012-05-25
2012-05-26
2012-05-27
2012-05-28
2012-05-29
2012-05-30
2012-05-31
2012-06-01
2012-06-02
2012-06-03
2012-06-04
2012-06-05
2012-06-06
2012-06-07
2012-06-08
2012-06-09
2012-06-10
2012-06-11
2012-06-12
2012-06-13
2012-06-14
2012-06-15
2012-06-16
2012-06-17
2012-06-18
2012-06-19
2012-06-20
2012-06-21
2012-06-22
2012-06-23
2012-06-24
2012-06-25
2012-06-26
2012-06-27
2012-06-28
2012-06-29
2012-06-30
2012-07-01
2012-07-02
2012-07-03
2012-07-04
2012-07-04 failed
2012-07-05
2012-07-06
2012-07-07
2012-07-08
2012-07-09
2012-07-10
2012-07-11
2012-07-11 failed
2012-07-12
2012-07-13
2012-07-14
2012-07-15
2012-07-16
2012-07-17
2012-07-18
2012-07-19
2012-07-20
2012-07-21
2012-07-22
2012-07-23
2012-07-24
2012-07-25
2012-07-26
2012-07-27
2012-07-28
2012-07-29
2012-07-30
2012-07-31
2012-08-01
2012-08-02
2012-08-03
2012-08-04
2012-08-05
2012-08-06
2012-08-07
2012-08-08
2012-08-09
2012-08-10
2012-08-11
2012-08-12
2012-08-13
2012-08-14
2012-08-15
2012-08-16
2012-08-16 failed
2012-08-17
2012-08-18
2012-08-19
2012-08-20
2012-08-21
2012-08-22
2012-08-23
2012-08-24
2012-08-25
2012-08-26
2012-08-27
2012-08-28
2012-08-29
2012-08-30
2012-08-31
2012-09-01
2012-09-02
2012-09-03
2012-09-04
2012-09-05
2012-09-06
2012-09-07
2012-09-08
2012-09-09
2012-09-10
2012-09-11
2012-09-12
2012-09-12 failed
2012-09-13
2012-09-14
2012-09-15
2012-09-16
2012-09-17
2012-09-17 failed
2012-09-18
2012-09-19
2012-09-20
2012-09-21
2012-09-22
2012-09-23
2012-09-24
2012-09-25
2012-09-25 failed
2012-09-26
2012-09-27
2012-09-28
2012-09-29
2012-09-30
2012-10-01
2012-10-02
2012-10-02 failed
2012-10-03
2012-10-04
2012-10-05
2012-10-05 failed
2012-10-06
2012-10-07
2012-10-08
2012-10-08 failed
2012-10-09
2012-10-10
2012-10-11
2012-10-12
2012-10-13
2012-10-14
2012-10-15
2012-10-16
2012-10-17
2012-10-18
2012-10-19
2012-10-20
2012-10-21
2012-10-22
2012-10-23
2012-10-24
2012-10-25
2012-10-26
2012-10-27
2012-10-28
2012-10-29
2012-10-30
2012-10-31
2012-11-01
2012-11-02
2012-11-03
2012-11-04
2012-11-05
2012-11-06
2012-11-06 failed
2012-11-07
2012-11-08
2012-11-09
2012-11-10
2012-11-10 failed
2012-11-11
2012-11-12
2012-11-13
2012-11-14
2012-11-15
2012-11-16
2012-11-17
2012-11-18
2012-11-19
2012-11-20
2012-11-21
2012-11-22
2012-11-23
2012-11-23 failed
2012-11-24
2012-11-25
2012-11-26
2012-11-27
2012-11-28
2012-11-29
2012-11-30
2012-12-01
2012-12-02
2012-12-03
2012-12-04
2012-12-05
2012-12-06
2012-12-07
2012-12-07 failed
2012-12-08
2012-12-08 failed
2012-12-09
2012-12-10
2012-12-11
2012-12-11 failed
2012-12-12
2012-12-13
2012-12-14
2012-12-15
2012-12-16
2012-12-17
2012-12-18
2012-12-19
2012-12-20
2012-12-21
2012-12-22
2012-12-23
2012-12-24
2012-12-25
2012-12-26
2012-12-27
2012-12-28
2012-12-29
2012-12-30
2012-12-31
2012-12-31 failed

In [39]:
# Check list for failed requests
dts_chk

['2012-01-26',
 '2012-02-08',
 '2012-03-17',
 '2012-03-27',
 '2012-04-03',
 '2012-04-06',
 '2012-04-16',
 '2012-04-17',
 '2012-05-06',
 '2012-05-16',
 '2012-05-17',
 '2012-07-04',
 '2012-07-11',
 '2012-08-16',
 '2012-09-12',
 '2012-09-17',
 '2012-09-25',
 '2012-10-02',
 '2012-10-05',
 '2012-10-08',
 '2012-11-06',
 '2012-11-10',
 '2012-11-23',
 '2012-12-07',
 '2012-12-08',
 '2012-12-11',
 '2012-12-31']

In [40]:
# loop through failed dates and retrieve data and write to csv by date
for d in dts_chk:
    print(d)
    q_url = f"{url}datasetid={ds_id}&datatypeid={dt_id}&locationid={loc_id}&startdate={d}&enddate={d}&units=metric&limit={limit}"
    try: 
        response = requests.get(q_url, headers={'token': noaa_key}).json()
        df = pd.DataFrame(response['results'])
        df['station'] = df['station'].str.slice(6,17)
        df = df[['station','value']].rename(columns={'value':d})
        df.to_csv(f'outputs/prcp/{year}/csv/{d}.csv',index=False)
    except:
        dts_chk.append(d)
        print(f'{d} failed')
    time.sleep(1)

2012-01-26
2012-01-26 failed
2012-02-08
2012-03-17
2012-03-27
2012-04-03
2012-04-06
2012-04-16
2012-04-17
2012-05-06
2012-05-16
2012-05-17
2012-07-04
2012-07-11
2012-08-16
2012-09-12
2012-09-17
2012-09-25
2012-10-02
2012-10-05
2012-10-08
2012-11-06
2012-11-10
2012-11-23
2012-12-07
2012-12-08
2012-12-11
2012-12-31
2012-01-26

In [3]:
# Retrieve data by singular date for dates that failed second attempt to see if there are errors
d='2022-01-01'
q_url = f"{url}datasetid={ds_id}&datatypeid={dt_id}&locationid={loc_id}&startdate={d}&enddate={d}&units=metric&limit={limit}"
response = requests.get(q_url, headers={'token': noaa_key}).json()
df = pd.DataFrame(response['results'])
df

                    date datatype            station attributes  value
0    2022-01-01T00:00:00     PRCP  GHCND:US1CAAL0001   ,,N,0700    0.0
1    2022-01-01T00:00:00     PRCP  GHCND:US1CAAL0003   ,,N,0700    0.0
2    2022-01-01T00:00:00     PRCP  GHCND:US1CAAL0004   ,,N,0700    0.0
3    2022-01-01T00:00:00     PRCP  GHCND:US1CAAL0012   ,,N,0700    0.0
4    2022-01-01T00:00:00     PRCP  GHCND:US1CAAL0030   ,,N,0700    0.0
..                   ...      ...                ...        ...    ...
817  2022-01-01T00:00:00     PRCP  GHCND:USW00093230   ,,W,2400    0.0
818  2022-01-01T00:00:00     PRCP  GHCND:USW00093241   ,,W,2400    0.0
819  2022-01-01T00:00:00     PRCP  GHCND:USW00093242       ,,W,    0.0
820  2022-01-01T00:00:00     PRCP  GHCND:USW00093245       ,,R,    0.0
821  2022-01-01T00:00:00     PRCP  GHCND:USW00094299       ,,W,    0.0

[822 rows x 5 columns]

In [4]:
# Isolate station information to station id
df['station'] = df['station'].str.slice(6,17)
df = df[['station','value']].rename(columns={'value':d})
df

         station  2022-01-01
0    US1CAAL0001         0.0
1    US1CAAL0003         0.0
2    US1CAAL0004         0.0
3    US1CAAL0012         0.0
4    US1CAAL0030         0.0
..           ...         ...
817  USW00093230         0.0
818  USW00093241         0.0
819  USW00093242         0.0
820  USW00093245         0.0
821  USW00094299         0.0

[822 rows x 2 columns]

In [6]:
# export data to csv
df.to_csv(f'../outputs/prcp/{year}/csv/{d}.csv',index=False)